AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  java-aws-rest-api

  Sample SAM Template for java-aws-rest-api

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java17
    Architectures:
      - x86_64
    Environment:
      Variables:
        REGION: !Ref Region

Parameters:
  Region:
    Description: AWS Region
    Type: String
    Default: us-east-1
  CustomTag:
    Description: Custom tag
    Type: String
    Default: custom-tag

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Environment:
        Variables:
          CUSTOM_TAG: !Ref CustomTag

  GoodbyeWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: goodbyeworld.App::handleRequest
      Environment:
        Variables:
          PARAM1: VALUE

  ApiGateway:
    Type: AWS::Serverless::Api
    DependsOn: OpenApiExecutionRole
    Properties:
      Name: Test API Gateway
      StageName: Stage
      OpenApiVersion: '3.0.1'
      EndpointConfiguration:
        Type: REGIONAL
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: docs/openapispec.yaml

  OpenApiExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: open-api-execution-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
              Action:
                - sts:AssumeRole
      Policies:
        - PolicyName: OpenApiExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action: lambda:InvokeFunction
                Effect: Allow
                Resource:
                  - !Ref HelloWorldFunction.Alias
                  - !Ref GoodbyeWorldFunction.Alias

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
