openapi: 3.0.3
info:
  title: Hello World API
  description: |-
    Hello World based on the OpenAPI 3.0 specification.
  version: 0.0.1
paths:
  /hello:
    get:
      summary: Hello World
      description: Hello World API endpoint

      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: TODO.add.lambda.path
        httpMethod: GET