openapi: 3.0.3
info:
  title: Hello World API
  description: |-
    Hello World based on the OpenAPI 3.0 specification.
  version: 0.0.1
paths:
  /hello:
    get:
      summary: Hello World
      description: Hello World API endpoint

      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
      x-amazon-apigateway-integration:
        type: aws_proxy
        passThroughBehaviour: when_no_match
        httpMethod: GET
        credentials:
          'Fn::GetAtt':
            - OpenApiExecutionRole
            - Arn
        uri:
          'Fn::Sub': arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
